#!/usr/bin/env bash
# Transfers a file from our client to a server
#
# variables
path="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
filename=$(basename "$BASH_SOURCE")
brown='\e[0;33m'
resets='\003[0m'
file="$1"
ip="$2"
user="ubuntu"
key="$4"

if [ $# -eq 2 ]; then
  scp -i "$key" -o StrictHostKeyChecking=no "$path"/"$file" "$user"@"$ip":/home/"$user"/
else
  echo -e "Usage: ${brown}$filename PATH TO FILE IP USERNAME PATH TO SSH_KEY${resets}"
fi

